image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  - deploy

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: '*/*/'
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/bilosek/dotnet-app:$CI_COMMIT_REF_SLUG"
  IMAGE_NAME: "backend"
  IMAGE_TAG: "$CI_COMMIT_REF_SLUG"

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - $SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json
    - $SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*
    - $NUGET_PACKAGES_DIRECTORY
  policy: pull-push

before_script:
  - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  services:
    - docker:27.3.1-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - dotnet build --no-restore
    - docker build -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG
  only:
    - main

tests:
  stage: test
  script:
    - dotnet test --no-restore
  artifacts:
    paths:
      - '**/*.trx'
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Define your deployment script!"
  environment: production
