image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  - push
  - deploy

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: './'
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/dotnet:$CI_COMMIT_REF_SLUG"
  IMAGE_NAME: "backend"
  IMAGE_TAG: "$CI_COMMIT_REF_SLUG"

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - $SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json
    - $SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*
    - $NUGET_PACKAGES_DIRECTORY
  policy: pull-push

workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_ID' #merge
    - if: '$CI_COMMIT_BRANCH' #push

build:
  stage: build
  before_script:
    - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY
  script:
    - dotnet build --no-restore

test:
  stage: test
  before_script:
    - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY
  script:
    - dotnet test --no-restore

lint:
  stage: test
  before_script:
    - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet tool install -g dotnet-format
  script:
    - dotnet format ./Backend.sln --verify-no-changes

push:
  stage: push
  image: docker:27.3.1
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  image: docker:27.3.1
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker pull $DOCKER_IMAGE
    - docker save -o $IMAGE_NAME.tar $DOCKER_IMAGE
    - scp -i pz2_key.pem $IMAGE_NAME.tar pz2@74.234.194.80:/home/pz2/
    - ssh -i pz2_key.pem pz2@74.234.194.80 <<EOF
        docker load -i /home/pz2/$IMAGE_NAME.tar
        docker run -d -p 8080:80 $DOCKER_IMAGE
      EOF
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'    