image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
#  - build
#  - test
#  - push
  - deploy

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: './'
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/dotnet:$CI_COMMIT_REF_SLUG"
  IMAGE_NAME: "backend"
  IMAGE_TAG: "$CI_COMMIT_REF_SLUG"

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - $SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json
    - $SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*
    - $NUGET_PACKAGES_DIRECTORY
  policy: pull-push

workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_ID' #merge
    - if: '$CI_COMMIT_BRANCH' #push


deploy:
  stage: deploy
  image: docker:27.3.1
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "$SSH_PRIVATE_KEY" > pz2_key.pem
    - chmod 600 pz2_key.pem
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 74.234.194.80 >> ~/.ssh/known_hosts
  script:
    - docker pull $DOCKER_IMAGE
    - docker save -o $IMAGE_NAME.tar $DOCKER_IMAGE
    - scp -i pz2_key.pem $IMAGE_NAME.tar pz2@74.234.194.80:/home/pz2/
    - ssh -i pz2_key.pem pz2@74.234.194.80 sudo snap install docker
    - ssh -i pz2_key.pem pz2@74.234.194.80 "sudo docker stop \$(sudo docker ps -q) || true"
    - ssh -i pz2_key.pem pz2@74.234.194.80 "sudo docker rm \$(sudo docker ps -aq) || true"
    - ssh -i pz2_key.pem pz2@74.234.194.80 sudo docker load -i /home/pz2/$IMAGE_NAME.tar
    - ssh -i pz2_key.pem pz2@74.234.194.80 sudo docker run -d -p 7210:7210 -p 5084:5084 $DOCKER_IMAGE
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'    