stages:
  - lint
  - test
  - build
  - push

lint:
  stage: lint
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - echo "Running linter..."
    - dotnet format --check
  only:
    - main

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - echo "Running tests..."
    - dotnet test --no-build --verbosity normal
  artifacts:
    reports:
      junit: TestResults/*.xml
    paths:
      - TestResults/
  only:
    - main

build:
  stage: build
  image: docker:24.0
  services:
    - docker:24.0-dind
  script:
    - echo "Building Docker image..."
    - docker build -t registry.gitlab.com/ProjektZespolowy/backend:latest .
  only:
    - main

push:
  stage: push
  image: docker:24.0
  services:
    - docker:24.0-dind
  script:
    - echo "Pushing Docker image to GitLab Container Registry..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push registry.gitlab.com/ProjektZespolowy/backend:latest
  only:
    - main
